-
  name: Deploy Calculator WebApp to Remote Server
  hosts: target1
  vars:
    cal_file_path: /home/jatin/simple_calc_app
    dest_path: /var/www/html
  tasks:
    - 
      name: Installing Apache Server and Git on Target Servers
      yum: 
        name: "{{ item }}"
        state: present 
      loop:
        - git
        - httpd
    - 
      name: Starting Apache Server on Target Servers
      service: 
        name: httpd
        state: started 
    - 
      name: Loading Calculator App from Git Repo
      ansible.builtin.git:
        repo: 'https://github.com/dograjatin/Simple_Calculator.git'
        dest: "{{ cal_file_path }}"
        clone: yes
        
    - 
      name: Transferring Calc App to Apache Server
      shell: cp -r "{{ cal_file_path }}"/* "{{ dest_path }}"
      become: yes
      
    - 
      name: Checking Apache Server File Permissions
      ansible.builtin.file:
        path: "{{ dest_path }}"
        recurse: yes
        mode: 0777
    - 
      name: Configuring Firewall for HTTP Service
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled
    - 
      name: Reloading Firewall and Apache Server
      service: 
        name: "{{ item }}"
        state: reloaded 
      loop:
        - firewalld
        - httpd
      
